"""
PathoLens AI - Expanded Database Seed Script
Adds 100+ new bacterial species with comprehensive metadata.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import uuid
from app.core.database import SessionLocal, engine, Base
from app.core.security import get_password_hash
from app.models import *
from app.models.species import SpeciesDisease


NEW_SPECIES = [
    {"scientific_name": "Treponema pallidum", "common_name": "Syphilis spirochete", "phylum": "Spirochaetota", "class_name": "Spirochaetia", "order_name": "Spirochaetales", "family": "Treponemataceae", "genus": "Treponema", "species": "pallidum", "gram_stain": "negative", "shape": "spirochete", "size_micrometers": "6.0", "arrangement": "single", "oxygen_requirement": "anaerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human genital mucosa and skin", "culture_media": "Rabbit testes (in vivo only)", "biosafety_level": 2, "risk_level": "high", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": False, "description": "Causative agent of syphilis, a sexually transmitted infection with multiple clinical stages."},
    {"scientific_name": "Borrelia burgdorferi", "common_name": "Lyme spirochete", "phylum": "Spirochaetota", "class_name": "Spirochaetia", "order_name": "Spirochaetales", "family": "Borreliaceae", "genus": "Borrelia", "species": "burgdorferi", "gram_stain": "negative", "shape": "spirochete", "size_micrometers": "20.0", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 34.0, "habitat": "Ixodes tick vectors, mammalian hosts", "culture_media": "BSK-II medium", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": False, "description": "Causative agent of Lyme disease, transmitted by Ixodes ticks in North America, Europe, and Asia."},
    {"scientific_name": "Rickettsia rickettsii", "common_name": "RMSF agent", "phylum": "Pseudomonadota", "class_name": "Alphaproteobacteria", "order_name": "Rickettsiales", "family": "Rickettsiaceae", "genus": "Rickettsia", "species": "rickettsii", "gram_stain": "negative", "shape": "coccobacillus", "size_micrometers": "0.3", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 34.0, "habitat": "Dermacentor tick vectors", "culture_media": "Vero cells (intracellular)", "biosafety_level": 3, "risk_level": "critical", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": False, "description": "Causative agent of Rocky Mountain spotted fever, a potentially fatal tick-borne rickettsial disease."},
    {"scientific_name": "Chlamydia trachomatis", "common_name": "Chlamydia", "phylum": "Chlamydiota", "class_name": "Chlamydiia", "order_name": "Chlamydiales", "family": "Chlamydiaceae", "genus": "Chlamydia", "species": "trachomatis", "gram_stain": "negative", "shape": "coccus", "size_micrometers": "0.3", "arrangement": "elementary/reticulate bodies", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human urogenital tract and conjunctiva", "culture_media": "McCoy cells or HEp-2 cells", "biosafety_level": 2, "risk_level": "high", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": False, "description": "Most common bacterial STI worldwide; causes trachoma (leading infectious cause of blindness), urethritis, and pelvic inflammatory disease."},
    {"scientific_name": "Legionella pneumophila", "common_name": "Legionella", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Legionellales", "family": "Legionellaceae", "genus": "Legionella", "species": "pneumophila", "gram_stain": "negative", "shape": "coccobacillus", "size_micrometers": "2.0", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 35.0, "habitat": "Freshwater aquatic environments, cooling towers", "culture_media": "BCYE (buffered charcoal yeast extract)", "biosafety_level": 2, "risk_level": "high", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": False, "description": "Causative agent of Legionnaires disease and Pontiac fever, transmitted via aerosolized water."},
    {"scientific_name": "Bordetella pertussis", "common_name": "Whooping cough bacterium", "phylum": "Pseudomonadota", "class_name": "Betaproteobacteria", "order_name": "Burkholderiales", "family": "Alcaligenaceae", "genus": "Bordetella", "species": "pertussis", "gram_stain": "negative", "shape": "coccobacillus", "size_micrometers": "0.5", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human respiratory tract", "culture_media": "Regan-Lowe charcoal agar", "biosafety_level": 2, "risk_level": "high", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": False, "description": "Causative agent of pertussis (whooping cough), a highly contagious respiratory disease."},
    {"scientific_name": "Corynebacterium diphtheriae", "common_name": "Diphtheria bacillus", "phylum": "Actinomycetota", "class_name": "Actinomycetes", "order_name": "Corynebacteriales", "family": "Corynebacteriaceae", "genus": "Corynebacterium", "species": "diphtheriae", "gram_stain": "positive", "shape": "club-shaped rod", "size_micrometers": "3.0", "arrangement": "palisades", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human respiratory tract and skin", "culture_media": "Tinsdale or Loeffler serum agar", "biosafety_level": 2, "risk_level": "high", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": False, "description": "Causative agent of diphtheria, producing a potent exotoxin causing pseudomembrane formation in the throat."},
    {"scientific_name": "Helicobacter pylori", "common_name": "H. pylori", "phylum": "Campylobacterota", "class_name": "Campylobacteria", "order_name": "Campylobacterales", "family": "Helicobacteraceae", "genus": "Helicobacter", "species": "pylori", "gram_stain": "negative", "shape": "spiral", "size_micrometers": "3.0", "arrangement": "single", "oxygen_requirement": "microaerophile", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human gastric mucosa", "culture_media": "Skirrow agar, Columbia blood agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": False, "description": "Causative agent of peptic ulcers and gastritis; classified as a Group 1 carcinogen for gastric cancer."},
    {"scientific_name": "Leptospira interrogans", "common_name": "Leptospira", "phylum": "Spirochaetota", "class_name": "Leptospirae", "order_name": "Leptospirales", "family": "Leptospiraceae", "genus": "Leptospira", "species": "interrogans", "gram_stain": "negative", "shape": "spirochete", "size_micrometers": "10.0", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 30.0, "habitat": "Freshwater, soil, animal urine", "culture_media": "EMJH medium", "biosafety_level": 2, "risk_level": "high", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": False, "description": "Causative agent of leptospirosis, a zoonotic disease transmitted through contact with infected animal urine."},
    {"scientific_name": "Brucella melitensis", "common_name": "Brucella", "phylum": "Pseudomonadota", "class_name": "Alphaproteobacteria", "order_name": "Hyphomicrobiales", "family": "Phyllobacteriaceae", "genus": "Brucella", "species": "melitensis", "gram_stain": "negative", "shape": "coccobacillus", "size_micrometers": "0.6", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Goats, sheep, cattle, humans", "culture_media": "Brucella agar, chocolate agar", "biosafety_level": 3, "risk_level": "critical", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": False, "description": "Causative agent of brucellosis, a zoonotic disease causing undulant fever, joint pain, and chronic fatigue."},
    {"scientific_name": "Coxiella burnetii", "common_name": "Q fever agent", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Legionellales", "family": "Coxiellaceae", "genus": "Coxiella", "species": "burnetii", "gram_stain": "negative", "shape": "coccobacillus", "size_micrometers": "0.4", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Livestock, ticks, contaminated soil", "culture_media": "Vero cells (obligate intracellular)", "biosafety_level": 3, "risk_level": "critical", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": False, "description": "Causative agent of Q fever, causing acute flu-like illness and chronic endocarditis."},
    {"scientific_name": "Acinetobacter baumannii", "common_name": "Acinetobacter", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Pseudomonadales", "family": "Moraxellaceae", "genus": "Acinetobacter", "species": "baumannii", "gram_stain": "negative", "shape": "coccobacillus", "size_micrometers": "1.5", "arrangement": "pairs", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Hospital environments, soil, water", "culture_media": "MacConkey agar, blood agar", "biosafety_level": 2, "risk_level": "critical", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Major nosocomial pathogen causing ventilator-associated pneumonia and bloodstream infections; ESKAPE pathogen with extensive multidrug resistance."},
    {"scientific_name": "Stenotrophomonas maltophilia", "common_name": "Stenotrophomonas", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Pseudomonadales", "family": "Xanthomonadaceae", "genus": "Stenotrophomonas", "species": "maltophilia", "gram_stain": "negative", "shape": "rod", "size_micrometers": "1.5", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Hospital water systems, soil, plants", "culture_media": "MacConkey agar, S maltophilia selective agar", "biosafety_level": 2, "risk_level": "high", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Emerging multidrug-resistant nosocomial pathogen causing pneumonia and bloodstream infections in immunocompromised patients."},
    {"scientific_name": "Moraxella catarrhalis", "common_name": "Moraxella", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Pseudomonadales", "family": "Moraxellaceae", "genus": "Moraxella", "species": "catarrhalis", "gram_stain": "negative", "shape": "diplococcus", "size_micrometers": "0.8", "arrangement": "diplococci", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human nasopharynx", "culture_media": "Chocolate agar, blood agar", "biosafety_level": 1, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Common nasopharyngeal commensal that causes otitis media, sinusitis, and lower respiratory tract infections."},
    {"scientific_name": "Gardnerella vaginalis", "common_name": "Gardnerella", "phylum": "Actinomycetota", "class_name": "Actinomycetes", "order_name": "Actinomycetales", "family": "Bifidobacteriaceae", "genus": "Gardnerella", "species": "vaginalis", "gram_stain": "variable", "shape": "coccobacillus", "size_micrometers": "1.0", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human vaginal microbiome", "culture_media": "V琼脂 (V琼脂), Columbia blood agar", "biosafety_level": 1, "risk_level": "low", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Primary bacterial species associated with bacterial vaginosis, forming biofilms on vaginal epithelium."},
    {"scientific_name": "Mycoplasma pneumoniae", "common_name": "Walking pneumonia agent", "phylum": "Mollicutes", "class_name": "Mollicutes", "order_name": "Mycoplasmatales", "family": "Mycoplasmataceae", "genus": "Mycoplasma", "species": "pneumoniae", "gram_stain": "negative", "shape": "pleomorphic", "size_micrometers": "0.3", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human respiratory tract", "culture_media": "SP4 or Hayflick medium", "biosafety_level": 1, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": False, "description": "Causative agent of atypical pneumonia (walking pneumonia) and bronchitis, lacking a cell wall."},
    {"scientific_name": "Proteus mirabilis", "common_name": "Proteus", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Enterobacterales", "family": "Enterobacteriaceae", "genus": "Proteus", "species": "mirabilis", "gram_stain": "negative", "shape": "rod", "size_micrometers": "2.0", "arrangement": "single", "oxygen_requirement": "facultative anaerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human gastrointestinal tract, soil, water", "culture_media": "MacConkey agar, SS agar", "biosafety_level": 1, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Major cause of catheter-associated UTIs, notable for swarming motility and urease production leading to kidney stones."},
    {"scientific_name": "Klebsiella oxytoca", "common_name": "Klebsiella oxytoca", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Enterobacterales", "family": "Enterobacteriaceae", "genus": "Klebsiella", "species": "oxytoca", "gram_stain": "negative", "shape": "rod", "size_micrometers": "1.5", "arrangement": "single", "oxygen_requirement": "facultative anaerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human gut, soil, water", "culture_media": "MacConkey agar", "biosafety_level": 2, "risk_level": "high", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Nosocomial pathogen causing pneumonia, UTIs, and antibiotic-associated hemorrhagic colitis via indole production."},
    {"scientific_name": "Serratia marcescens", "common_name": "Serratia", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Enterobacterales", "family": "Yersiniaceae", "genus": "Serratia", "species": "marcescens", "gram_stain": "negative", "shape": "rod", "size_micrometers": "1.5", "arrangement": "single", "oxygen_requirement": "facultative anaerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 30.0, "habitat": "Soil, water, hospital environments", "culture_media": "MacConkey agar, blood agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Environmental organism causing nosocomial infections; produces red prodigiosin pigment at room temperature."},
    {"scientific_name": "Citrobacter freundii", "common_name": "Citrobacter", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Enterobacterales", "family": "Enterobacteriaceae", "genus": "Citrobacter", "species": "freundii", "gram_stain": "negative", "shape": "rod", "size_micrometers": "2.0", "arrangement": "single", "oxygen_requirement": "facultative anaerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human gut, soil, water", "culture_media": "MacConkey agar, EMB agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Opportunistic pathogen causing UTIs, respiratory infections, and neonatal meningitis."},
    {"scientific_name": "Enterobacter aerogenes", "common_name": "Enterobacter", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Enterobacterales", "family": "Enterobacteriaceae", "genus": "Enterobacter", "species": "aerogenes", "gram_stain": "negative", "shape": "rod", "size_micrometers": "2.0", "arrangement": "single", "oxygen_requirement": "facultative anaerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human gut, soil, water, sewage", "culture_media": "MacConkey agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "ESKAPE pathogen causing nosocomial UTIs, pneumonia, and bloodstream infections."},
    {"scientific_name": "Morganella morganii", "common_name": "Morganella", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Enterobacterales", "family": "Morganellaceae", "genus": "Morganella", "species": "morganii", "gram_stain": "negative", "shape": "rod", "size_micrometers": "1.5", "arrangement": "single", "oxygen_requirement": "facultative anaerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human gut, soil, water", "culture_media": "MacConkey agar, SS agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Opportunistic pathogen causing UTIs and wound infections, with strong urease production."},
    {"scientific_name": "Aeromonas hydrophila", "common_name": "Aeromonas", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Aeromonadales", "family": "Aeromonadaceae", "genus": "Aeromonas", "species": "hydrophila", "gram_stain": "negative", "shape": "rod", "size_micrometers": "1.5", "arrangement": "single", "oxygen_requirement": "facultative anaerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Freshwater, brackish water", "culture_media": "Blood agar, MacConkey agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Waterborne pathogen causing gastroenteritis, wound infections, and septicemia, especially in immunocompromised individuals."},
    {"scientific_name": "Vibrio vulnificus", "common_name": "Flesh-eating vibrio", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Vibrionales", "family": "Vibrionaceae", "genus": "Vibrio", "species": "vulnificus", "gram_stain": "negative", "shape": "comma-shaped", "size_micrometers": "2.0", "arrangement": "single", "oxygen_requirement": "facultative anaerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Warm seawater, shellfish", "culture_media": "TCBS agar, blood agar", "biosafety_level": 2, "risk_level": "critical", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": False, "description": "Highly virulent marine pathogen causing necrotizing wound infections and primary septicemia, especially in liver disease patients."},
    {"scientific_name": "Vibrio parahaemolyticus", "common_name": "Vibrio parahaemolyticus", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Vibrionales", "family": "Vibrionaceae", "genus": "Vibrio", "species": "parahaemolyticus", "gram_stain": "negative", "shape": "comma-shaped", "size_micrometers": "2.0", "arrangement": "single", "oxygen_requirement": "facultative anaerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Marine and estuarine environments", "culture_media": "TCBS agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": False, "description": "Leading cause of seafood-borne gastroenteritis worldwide, associated with raw or undercooked shellfish."},
    {"scientific_name": "Streptococcus agalactiae", "common_name": "Group B Strep", "phylum": "Bacillota", "class_name": "Bacilli", "order_name": "Lactobacillales", "family": "Streptococcaceae", "genus": "Streptococcus", "species": "agalactiae", "gram_stain": "positive", "shape": "coccus", "size_micrometers": "1.0", "arrangement": "chains and pairs", "oxygen_requirement": "facultative anaerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human gastrointestinal and vaginal tract", "culture_media": "Blood agar, CAMP test", "biosafety_level": 2, "risk_level": "high", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Leading cause of neonatal sepsis, meningitis, and pneumonia; screening recommended during pregnancy."},
    {"scientific_name": "Staphylococcus epidermidis", "common_name": "Coagulase-negative Staph", "phylum": "Bacillota", "class_name": "Bacilli", "order_name": "Bacillales", "family": "Staphylococcaceae", "genus": "Staphylococcus", "species": "epidermidis", "gram_stain": "positive", "shape": "coccus", "size_micrometers": "1.0", "arrangement": "grape-like clusters", "oxygen_requirement": "facultative anaerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human skin and mucous membranes", "culture_media": "Mannitol salt agar", "biosafety_level": 1, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Normal skin flora that causes biofilm-associated infections on medical devices such as catheters and prosthetic joints."},
    {"scientific_name": "Staphylococcus saprophyticus", "common_name": "Staph saprophyticus", "phylum": "Bacillota", "class_name": "Bacilli", "order_name": "Bacillales", "family": "Staphylococcaceae", "genus": "Staphylococcus", "species": "saprophyticus", "gram_stain": "positive", "shape": "coccus", "size_micrometers": "1.0", "arrangement": "grape-like clusters", "oxygen_requirement": "facultative anaerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human urogenital tract", "culture_media": "Mannitol salt agar (novobiocin resistant)", "biosafety_level": 1, "risk_level": "low", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Common cause of uncomplicated urinary tract infections in young sexually active women."},
    {"scientific_name": "Neisseria gonorrhoeae", "common_name": "Gonococcus", "phylum": "Pseudomonadota", "class_name": "Betaproteobacteria", "order_name": "Neisseriales", "family": "Neisseriaceae", "genus": "Neisseria", "species": "gonorrhoeae", "gram_stain": "negative", "shape": "diplococcus", "size_micrometers": "0.8", "arrangement": "diplococci", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human urogenital tract and pharynx", "culture_media": "Chocolate agar, Thayer-Martin selective agar", "biosafety_level": 2, "risk_level": "high", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": False, "description": "Causative agent of gonorrhea, increasingly exhibiting multidrug resistance (superbug)."},
    {"scientific_name": "Bartonella henselae", "common_name": "Cat scratch disease agent", "phylum": "Pseudomonadota", "class_name": "Alphaproteobacteria", "order_name": "Hyphomicrobiales", "family": "Bartonellaceae", "genus": "Bartonella", "species": "henselae", "gram_stain": "negative", "shape": "coccobacillus", "size_micrometers": "1.0", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Cat fleas, cat blood", "culture_media": "Chocolate agar, Columbia blood agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Causative agent of cat scratch disease, causing lymphadenopathy and fever after cat scratches or bites."},
    {"scientific_name": "Bartonella quintana", "common_name": "Trench fever agent", "phylum": "Pseudomonadota", "class_name": "Alphaproteobacteria", "order_name": "Hyphomicrobiales", "family": "Bartonellaceae", "genus": "Bartonella", "species": "quintana", "gram_stain": "negative", "shape": "coccobacillus", "size_micrometers": "1.0", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human body louse vector", "culture_media": "Chocolate agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Causative agent of trench fever, historically significant in wartime; transmitted by human body lice."},
    {"scientific_name": "Cutibacterium acnes", "common_name": "Acne bacterium", "phylum": "Actinomycetota", "class_name": "Actinomycetes", "order_name": "Corynebacteriales", "family": "Cutibacteriaceae", "genus": "Cutibacterium", "species": "acnes", "gram_stain": "positive", "shape": "rod", "size_micrometers": "1.5", "arrangement": "single", "oxygen_requirement": "anaerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human skin sebaceous follicles", "culture_media": "Anaerobic blood agar", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": True, "is_opportunistic": True, "description": "Normal skin commensal implicated in acne vulgaris; also causes device-associated infections."},
    {"scientific_name": "Fusobacterium nucleatum", "common_name": "Fusobacterium", "phylum": "Fusobacteriota", "class_name": "Fusobacteriia", "order_name": "Fusobacteriales", "family": "Fusobacteriaceae", "genus": "Fusobacterium", "species": "nucleatum", "gram_stain": "negative", "shape": "spindle-shaped", "size_micrometers": "5.0", "arrangement": "single", "oxygen_requirement": "anaerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human oral cavity and gut", "culture_media": "Anaerobic blood agar, Fastidious Anaerobe Agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Keystone periodontal pathogen strongly linked to colorectal cancer and adverse pregnancy outcomes."},
    {"scientific_name": "Porphyromonas gingivalis", "common_name": "P. gingivalis", "phylum": "Bacteroidota", "class_name": "Bacteroidia", "order_name": "Bacteroidales", "family": "Porphyromonadaceae", "genus": "Porphyromonas", "species": "gingivalis", "gram_stain": "negative", "shape": "rod", "size_micrometers": "1.5", "arrangement": "single", "oxygen_requirement": "anaerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human subgingival crevice", "culture_media": "Anaerobic blood agar, Brucella blood agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Major keystone pathogen in chronic periodontitis; produces gingipain proteases that degrade host tissues."},
    {"scientific_name": "Bacteroides fragilis", "common_name": "B. fragilis", "phylum": "Bacteroidota", "class_name": "Bacteroidia", "order_name": "Bacteroidales", "family": "Bacteroidaceae", "genus": "Bacteroides", "species": "fragilis", "gram_stain": "negative", "shape": "rod", "size_micrometers": "1.5", "arrangement": "single", "oxygen_requirement": "anaerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human colon", "culture_media": "Anaerobic blood agar, Bacteroides bile esculin agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": True, "is_pathogenic": True, "is_opportunistic": True, "description": "Dominant gut commensal that becomes a serious pathogen when displaced, causing intra-abdominal abscesses."},
    {"scientific_name": "Treponema denticola", "common_name": "T. denticola", "phylum": "Spirochaetota", "class_name": "Spirochaetia", "order_name": "Spirochaetales", "family": "Treponemataceae", "genus": "Treponema", "species": "denticola", "gram_stain": "negative", "shape": "spirochete", "size_micrometers": "0.2", "arrangement": "single", "oxygen_requirement": "anaerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human oral subgingival plaque", "culture_media": "Oral anaerobic medium", "biosafety_level": 1, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Red complex periodontal pathogen; produces dentilisin protease complex disrupting epithelial tight junctions."},
    {"scientific_name": "Prevotella intermedia", "common_name": "Prevotella", "phylum": "Bacteroidota", "class_name": "Bacteroidia", "order_name": "Bacteroidales", "family": "Prevotellaceae", "genus": "Prevotella", "species": "intermedia", "gram_stain": "negative", "shape": "rod", "size_micrometers": "1.5", "arrangement": "single", "oxygen_requirement": "anaerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human oral cavity, respiratory tract", "culture_media": "Anaerobic blood agar", "biosafety_level": 1, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Black-pigmented anaerobe associated with periodontal disease, pregnancy gingivitis, and respiratory infections."},
    {"scientific_name": "Faecalibacterium prausnitzii", "common_name": "F. prausnitzii", "phylum": "Bacillota", "class_name": "Clostridia", "order_name": "Eubacteriales", "family": "Oxalobacteraceae", "genus": "Faecalibacterium", "species": "prausnitzii", "gram_stain": "positive", "shape": "rod", "size_micrometers": "3.0", "arrangement": "single", "oxygen_requirement": "anaerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human colon", "culture_media": "Anaerobic blood agar with fructose", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Most abundant anti-inflammatory bacterium in the human gut; major butyrate producer protective against IBD."},
    {"scientific_name": "Roseburia intestinalis", "common_name": "Roseburia", "phylum": "Bacillota", "class_name": "Clostridia", "order_name": "Eubacteriales", "family": "Lachnospiraceae", "genus": "Roseburia", "species": "intestinalis", "gram_stain": "positive", "shape": "rod", "size_micrometers": "2.0", "arrangement": "single", "oxygen_requirement": "anaerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human colon", "culture_media": "Anaerobic blood agar", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Key butyrate-producing gut bacterium associated with improved metabolic health and reduced inflammation."},
    {"scientific_name": "Ruminococcus bromii", "common_name": "R. bromii", "phylum": "Bacillota", "class_name": "Clostridia", "order_name": "Eubacteriales", "family": "Ruminococcaceae", "genus": "Ruminococcus", "species": "bromii", "gram_stain": "positive", "shape": "coccus", "size_micrometers": "1.0", "arrangement": "tetrads", "oxygen_requirement": "anaerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human colon", "culture_media": "Anaerobic starch medium", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Keystone degrader of resistant starch in the human colon, essential for cross-feeding gut microbiome networks."},
    {"scientific_name": "Eggerthella lenta", "common_name": "E. lenta", "phylum": "Actinomycetota", "class_name": "Actinomycetes", "order_name": "Coriobacteriales", "family": "Eggerthellaceae", "genus": "Eggerthella", "species": "lenta", "gram_stain": "positive", "shape": "rod", "size_micrometers": "2.0", "arrangement": "single", "oxygen_requirement": "anaerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human colon", "culture_media": "Anaerobic blood agar", "biosafety_level": 1, "risk_level": "low", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Gut bacterium that inactivates the cardiac drug digoxin; also implicated in trimethylamine N-oxide (TMAO) production linked to cardiovascular disease."},
    {"scientific_name": "Streptomyces griseus", "common_name": "Streptomycin producer", "phylum": "Actinomycetota", "class_name": "Actinomycetes", "order_name": "Streptomycetales", "family": "Streptomycetaceae", "genus": "Streptomyces", "species": "griseus", "gram_stain": "positive", "shape": "filamentous", "size_micrometers": "0.8", "arrangement": "branching filaments", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": True, "growth_temperature_optimal": 28.0, "habitat": "Soil", "culture_media": "International Streptomyces Project agar", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Source of streptomycin, the first antibiotic effective against tuberculosis; model organism for antibiotic production."},
    {"scientific_name": "Bacillus thuringiensis", "common_name": "Bt", "phylum": "Bacillota", "class_name": "Bacilli", "order_name": "Bacillales", "family": "Bacillaceae", "genus": "Bacillus", "species": "thuringiensis", "gram_stain": "positive", "shape": "rod", "size_micrometers": "4.0", "arrangement": "chains", "oxygen_requirement": "aerobe", "motility": "motile", "spore_formation": True, "growth_temperature_optimal": 30.0, "habitat": "Soil, insect cadavers", "culture_media": "Nutrient agar, TBAB agar", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Produces crystalline (Cry) proteins toxic to insects; widely used as biological pesticide in organic farming."},
    {"scientific_name": "Deinococcus radiodurans", "common_name": "Conan the Bacterium", "phylum": "Deinococcota", "class_name": "Deinococci", "order_name": "Deinococcales", "family": "Deinococcaceae", "genus": "Deinococcus", "species": "radiodurans", "gram_stain": "positive", "shape": "coccus", "size_micrometers": "2.5", "arrangement": "tetrads", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 30.0, "habitat": "Soil, granite, desert environments", "culture_media": "TGY agar", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Most radiation-resistant organism known; can survive extreme doses of ionizing radiation through efficient DNA repair mechanisms."},
    {"scientific_name": "Geobacter sulfurreducens", "common_name": "Geobacter", "phylum": "Desulfobacterota", "class_name": "Desulfobacteria", "order_name": "Desulfobacterales", "family": "Geobacteraceae", "genus": "Geobacter", "species": "sulfurreducens", "gram_stain": "negative", "shape": "rod", "size_micrometers": "2.0", "arrangement": "single", "oxygen_requirement": "anaerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 30.0, "habitat": "Subsurface sediments, aquatic environments", "culture_media": "Anoxic freshwater medium", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Electroactive bacterium that transfers electrons to electrodes; key organism for microbial fuel cells and bioremediation."},
    {"scientific_name": "Shewanella oneidensis", "common_name": "Shewanella", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Alteromonadales", "family": "Shewanellaceae", "genus": "Shewanella", "species": "oneidensis", "gram_stain": "negative", "shape": "rod", "size_micrometers": "2.0", "arrangement": "single", "oxygen_requirement": "facultative anaerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 30.0, "habitat": "Freshwater lake sediments", "culture_media": "LB agar, TGY agar", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Model organism for extracellular electron transfer and metal reduction; important for bioremediation and bioelectronics."},
    {"scientific_name": "Azotobacter vinelandii", "common_name": "Azotobacter", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Pseudomonadales", "family": "Pseudomonadaceae", "genus": "Azotobacter", "species": "vinelandii", "gram_stain": "negative", "shape": "rod", "size_micrometers": "2.5", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 30.0, "habitat": "Soil", "culture_media": "Ashby's nitrogen-free agar", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Free-living nitrogen-fixing bacterium important in agriculture; model for nitrogenase enzyme research."},
    {"scientific_name": "Rhizobium leguminosarum", "common_name": "Rhizobium", "phylum": "Pseudomonadota", "class_name": "Alphaproteobacteria", "order_name": "Hyphomicrobiales", "family": "Rhizobiaceae", "genus": "Rhizobium", "species": "leguminosarum", "gram_stain": "negative", "shape": "rod", "size_micrometers": "1.5", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 28.0, "habitat": "Legume root nodules, soil", "culture_media": "YEM agar", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Symbiotic nitrogen-fixing bacterium forming root nodules on legumes; critical for sustainable agriculture."},
    {"scientific_name": "Bradyrhizobium japonicum", "common_name": "Bradyrhizobium", "phylum": "Pseudomonadota", "class_name": "Alphaproteobacteria", "order_name": "Hyphomicrobiales", "family": "Bradyrhizobiaceae", "genus": "Bradyrhizobium", "species": "japonicum", "gram_stain": "negative", "shape": "rod", "size_micrometers": "1.0", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 28.0, "habitat": "Soybean root nodules", "culture_media": "YEM agar", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Symbiotic nitrogen-fixer specific to soybeans; essential for global soybean production."},
    {"scientific_name": "Agrobacterium tumefaciens", "common_name": "Agrobacterium", "phylum": "Pseudomonadota", "class_name": "Alphaproteobacteria", "order_name": "Hyphomicrobiales", "family": "Rhizobiaceae", "genus": "Agrobacterium", "species": "tumefaciens", "gram_stain": "negative", "shape": "rod", "size_micrometers": "1.5", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 28.0, "habitat": "Soil, plant wound sites", "culture_media": "YEM agar, LB agar", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Natural genetic engineer that transfers T-DNA to plants; tool for plant genetic engineering and transgenic crop production."},
    {"scientific_name": "Streptomyces avermitilis", "common_name": "Avermectin producer", "phylum": "Actinomycetota", "class_name": "Actinomycetes", "order_name": "Streptomycetales", "family": "Streptomycetaceae", "genus": "Streptomyces", "species": "avermitilis", "gram_stain": "positive", "shape": "filamentous", "size_micrometers": "0.8", "arrangement": "branching filaments", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": True, "growth_temperature_optimal": 28.0, "habitat": "Soil", "culture_media": "ISP medium", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Source of avermectin, the antiparasitic drug that earned the Nobel Prize; used globally against river blindness and lymphatic filariasis."},
    {"scientific_name": "Synechocystis sp.", "common_name": "Synechocystis", "phylum": "Cyanobacteria", "class_name": "Cyanophyceae", "order_name": "Synechococcales", "family": "Synechocystidaceae", "genus": "Synechocystis", "species": "sp. PCC 6803", "gram_stain": "negative", "shape": "coccus", "size_micrometers": "3.0", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 30.0, "habitat": "Freshwater environments", "culture_media": "BG-11 medium", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Model cyanobacterium for photosynthesis research, biofuel production, and synthetic biology."},
    {"scientific_name": "Thermus aquaticus", "common_name": "Taq polymerase source", "phylum": "Deinococcota", "class_name": "Deinococci", "order_name": "Thermales", "family": "Thermaceae", "genus": "Thermus", "species": "aquaticus", "gram_stain": "negative", "shape": "rod", "size_micrometers": "5.0", "arrangement": "filaments", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 72.0, "habitat": "Hot springs, thermal vents", "culture_media": "TYG or YT media", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Source of Taq DNA polymerase, the thermostable enzyme enabling PCR; revolutionized molecular biology and diagnostics."},
    {"scientific_name": "Bacillus licheniformis", "common_name": "B. licheniformis", "phylum": "Bacillota", "class_name": "Bacilli", "order_name": "Bacillales", "family": "Bacillaceae", "genus": "Bacillus", "species": "licheniformis", "gram_stain": "positive", "shape": "rod", "size_micrometers": "3.0", "arrangement": "chains", "oxygen_requirement": "aerobe", "motility": "motile", "spore_formation": True, "growth_temperature_optimal": 37.0, "habitat": "Soil, bird feathers", "culture_media": "Nutrient agar", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Industrial workhorse for enzyme production (amylases, proteases) and antibiotic synthesis; GRAS organism."},
    {"scientific_name": "Bacillus megaterium", "common_name": "B. megaterium", "phylum": "Bacillota", "class_name": "Bacilli", "order_name": "Bacillales", "family": "Bacillaceae", "genus": "Bacillus", "species": "megaterium", "gram_stain": "positive", "shape": "rod", "size_micrometers": "4.0", "arrangement": "chains", "oxygen_requirement": "aerobe", "motility": "motile", "spore_formation": True, "growth_temperature_optimal": 30.0, "habitat": "Soil", "culture_media": "Nutrient agar", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "One of the largest known bacteria; used for phosphate solubilization, vitamin B12 production, and bioremediation."},
    {"scientific_name": "Propionibacterium freudenreichii", "common_name": "Propionibacterium", "phylum": "Actinomycetota", "class_name": "Actinomycetes", "order_name": "Propionibacteriales", "family": "Propionibacteriaceae", "genus": "Propionibacterium", "species": "freudenreichii", "gram_stain": "positive", "shape": "rod", "size_micrometers": "1.5", "arrangement": "single", "oxygen_requirement": "anaerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 30.0, "habitat": "Swiss cheese, dairy", "culture_media": "Reinforced clostridial agar", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Essential for Swiss cheese production, creating characteristic holes via CO2 production; also a probiotic."},
    {"scientific_name": "Leuconostoc mesenteroides", "common_name": "Leuconostoc", "phylum": "Bacillota", "class_name": "Bacilli", "order_name": "Lactobacillales", "family": "Leuconostocaceae", "genus": "Leuconostoc", "species": "mesenteroides", "gram_stain": "positive", "shape": "coccus", "size_micrometers": "1.0", "arrangement": "chains", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 25.0, "habitat": "Plants, fermented foods", "culture_media": "MRS agar", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Primary starter culture for sauerkraut, kimchi, and sourdough; produces dextran and CO2 for leavening."},
    {"scientific_name": "Pediococcus acidilactici", "common_name": "Pediococcus", "phylum": "Bacillota", "class_name": "Bacilli", "order_name": "Lactobacillales", "family": "Lactobacillaceae", "genus": "Pediococcus", "species": "acidilactici", "gram_stain": "positive", "shape": "coccus", "size_micrometers": "0.8", "arrangement": "tetrads", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Fermented foods, plants", "culture_media": "MRS agar", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Lactic acid bacterium used in meat fermentation, silage production, and as a probiotic for gut health."},
    {"scientific_name": "Oenococcus oeni", "common_name": "Oenococcus", "phylum": "Bacillota", "class_name": "Bacilli", "order_name": "Lactobacillales", "family": "Leuconostocaceae", "genus": "Oenococcus", "species": "oeni", "gram_stain": "positive", "shape": "coccus", "size_micrometers": "1.0", "arrangement": "chains", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 30.0, "habitat": "Wine", "culture_media": "Tomato juice agar, MLO medium", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Primary bacterium for malolactic fermentation in winemaking, reducing acidity and improving flavor."},
    {"scientific_name": "Enterococcus faecium", "common_name": "E. faecium", "phylum": "Bacillota", "class_name": "Bacilli", "order_name": "Lactobacillales", "family": "Enterococcaceae", "genus": "Enterococcus", "species": "faecium", "gram_stain": "positive", "shape": "coccus", "size_micrometers": "0.8", "arrangement": "pairs", "oxygen_requirement": "facultative anaerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human gastrointestinal tract", "culture_media": "Bile esculin agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": True, "is_pathogenic": True, "is_opportunistic": True, "description": "Dual nature: used as probiotic (E. coli Nissle 1917 analog) but also VRE causing hospital infections."},
    {"scientific_name": "Desulfovibrio desulfuricans", "common_name": "Desulfovibrio", "phylum": "Desulfobacterota", "class_name": "Desulfovibrio", "order_name": "Desulfovibrionales", "family": "Desulfovibrionaceae", "genus": "Desulfovibrio", "species": "desulfuricans", "gram_stain": "negative", "shape": "curved rod", "size_micrometers": "3.0", "arrangement": "single", "oxygen_requirement": "anaerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 30.0, "habitat": "Marine and freshwater sediments", "culture_media": "Postgate medium", "biosafety_level": 1, "risk_level": "low", "is_beneficial": False, "is_pathogenic": False, "is_opportunistic": False, "description": "Sulfate-reducing bacterium important in biogeochemical sulfur cycle and biocorrosion of metals."},
    {"scientific_name": "Chromobacterium violaceum", "common_name": "Chromobacterium", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Neisseriales", "family": "Chromobacteriaceae", "genus": "Chromobacterium", "species": "violaceum", "gram_stain": "negative", "shape": "rod", "size_micrometers": "2.0", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 30.0, "habitat": "Soil, freshwater in tropical regions", "culture_media": "Nutrient agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Produces purple violacein pigment with antimicrobial and antitumor properties; occasionally causes fatal septicemia."},
    {"scientific_name": "Sphingomonas paucimobilis", "common_name": "Sphingomonas", "phylum": "Pseudomonadota", "class_name": "Alphaproteobacteria", "order_name": "Sphingomonadales", "family": "Sphingomonadaceae", "genus": "Sphingomonas", "species": "paucimobilis", "gram_stain": "negative", "shape": "rod", "size_micrometers": "1.0", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 30.0, "habitat": "Soil, water, hospital environments", "culture_media": "Blood agar, MacConkey agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Environmental organism causing nosocomial infections; notable for yellow-pigmented colonies and sphingolipid-containing outer membrane."},
    {"scientific_name": "Kingella kingae", "common_name": "Kingella", "phylum": "Pseudomonadota", "class_name": "Betaproteobacteria", "order_name": "Neisseriales", "family": "Neisseriaceae", "genus": "Kingella", "species": "kingae", "gram_stain": "negative", "shape": "coccobacillus", "size_micrometers": "1.0", "arrangement": "pairs", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human oropharynx", "culture_media": "Chocolate agar, blood agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Leading cause of osteoarticular infections in young children; difficult to culture requiring CO2-enriched atmosphere."},
    {"scientific_name": "Micrococcus luteus", "common_name": "Micrococcus", "phylum": "Bacillota", "class_name": "Bacilli", "order_name": "Bacillales", "family": "Micrococcaceae", "genus": "Micrococcus", "species": "luteus", "gram_stain": "positive", "shape": "coccus", "size_micrometers": "0.8", "arrangement": "tetrads", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 30.0, "habitat": "Human skin, soil, water", "culture_media": "Blood agar, nutrient agar", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": True, "is_opportunistic": True, "description": "Ubiquitous skin commensal that occasionally causes infections in immunocompromised patients and prosthetic device infections."},
    {"scientific_name": "Rhodococcus equi", "common_name": "Rhodococcus", "phylum": "Actinomycetota", "class_name": "Actinomycetes", "order_name": "Corynebacteriales", "family": "Nocardiaceae", "genus": "Rhodococcus", "species": "equi", "gram_stain": "positive", "shape": "coccobacillus", "size_micrometers": "2.0", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Soil, horse manure", "culture_media": "Blood agar, MacConkey agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Important veterinary pathogen in foals; causes pneumonia in immunocompromised humans including HIV/AIDS patients."},
    {"scientific_name": "Nocardia asteroides", "common_name": "Nocardia", "phylum": "Actinomycetota", "class_name": "Actinomycetes", "order_name": "Corynebacteriales", "family": "Nocardiaceae", "genus": "Nocardia", "species": "asteroides", "gram_stain": "positive", "shape": "filamentous", "size_micrometers": "1.0", "arrangement": "branching filaments", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Soil, decaying vegetation", "culture_media": "Sabouraud agar, blood agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Causes nocardiosis, a pulmonary and systemic infection especially in immunocompromised individuals; partially acid-fast."},
    {"scientific_name": "Actinomyces israelii", "common_name": "Actinomyces", "phylum": "Actinomycetota", "class_name": "Actinomycetes", "order_name": "Actinomycetales", "family": "Actinomycetaceae", "genus": "Actinomyces", "species": "israelii", "gram_stain": "positive", "shape": "filamentous", "size_micrometers": "1.0", "arrangement": "branching filaments", "oxygen_requirement": "anaerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human oral cavity, GI tract", "culture_media": "Anaerobic blood agar, brain-heart infusion", "biosafety_level": 1, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Causative agent of actinomycosis, forming abscesses with characteristic sulfur granules in tissue."},
    {"scientific_name": "Eikenella corrodens", "common_name": "Eikenella", "phylum": "Pseudomonadota", "class_name": "Betaproteobacteria", "order_name": "Pseudomonadales", "family": "Neisseriaceae", "genus": "Eikenella", "species": "corrodens", "gram_stain": "negative", "shape": "coccobacillus", "size_micrometers": "1.0", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human oropharynx, GI tract", "culture_media": "Blood agar (pitting colonies)", "biosafety_level": 2, "risk_level": "low", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Causes infections following human bites and fist fights; characteristic corroding colonies on blood agar."},
    {"scientific_name": "Streptococcus gallolyticus", "common_name": "S. gallolyticus", "phylum": "Bacillota", "class_name": "Bacilli", "order_name": "Lactobacillales", "family": "Streptococcaceae", "genus": "Streptococcus", "species": "gallolyticus", "gram_stain": "positive", "shape": "coccus", "size_micrometers": "1.0", "arrangement": "chains", "oxygen_requirement": "facultative anaerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human GI tract", "culture_media": "Blood agar, bile esculin agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Associated with colorectal cancer and biliary tract infections; bile-tolerant streptococcus."},
    {"scientific_name": "Aerococcus urinae", "common_name": "Aerococcus", "phylum": "Bacillota", "class_name": "Bacilli", "order_name": "Lactobacillales", "family": "Aerococcaceae", "genus": "Aerococcus", "species": "urinae", "gram_stain": "positive", "shape": "coccus", "size_micrometers": "1.0", "arrangement": "tetrads and clusters", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human urinary tract", "culture_media": "Blood agar, CNA agar", "biosafety_level": 1, "risk_level": "low", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Emerging uropathogen often misidentified as streptococci; causes UTIs and endocarditis."},
    {"scientific_name": "Arcanobacterium haemolyticum", "common_name": "Arcanobacterium", "phylum": "Actinomycetota", "class_name": "Actinomycetes", "order_name": "Corynebacteriales", "family": "Actinomycetaceae", "genus": "Arcanobacterium", "species": "haemolyticum", "gram_stain": "positive", "shape": "rod", "size_micrometers": "1.5", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human pharynx, skin", "culture_media": "Blood agar (beta-hemolytic)", "biosafety_level": 2, "risk_level": "low", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": False, "description": "Causes pharyngitis in adolescents and young adults, sometimes accompanied by scarlatiniform rash."},
    {"scientific_name": "Providencia stuartii", "common_name": "Providencia", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Enterobacterales", "family": "Morganellaceae", "genus": "Providencia", "species": "stuartii", "gram_stain": "negative", "shape": "rod", "size_micrometers": "1.5", "arrangement": "single", "oxygen_requirement": "facultative anaerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Soil, water, hospital environments", "culture_media": "MacConkey agar, SS agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Common in burn units; causes UTIs and bacteremia in long-term care patients; intrinsically resistant to many antibiotics."},
    {"scientific_name": "Edwardsiella tarda", "common_name": "Edwardsiella", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Enterobacterales", "family": "Hafniaceae", "genus": "Edwardsiella", "species": "tarda", "gram_stain": "negative", "shape": "rod", "size_micrometers": "1.0", "arrangement": "single", "oxygen_requirement": "facultative anaerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Freshwater, fish, eels", "culture_media": "SS agar, MacConkey agar", "biosafety_level": 2, "risk_level": "medium", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Zoonotic pathogen causing gastroenteritis and wound infections, especially after contact with freshwater fish."},
    {"scientific_name": "Elizabethkingia anophelis", "common_name": "Elizabethkingia", "phylum": "Bacteroidota", "class_name": "Flavobacteriia", "order_name": "Flavobacteriales", "family": "Flavobacteriaceae", "genus": "Elizabethkingia", "species": "anophelis", "gram_stain": "negative", "shape": "rod", "size_micrometers": "1.5", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Hospital water systems, soil", "culture_media": "Blood agar, MacConkey agar", "biosafety_level": 2, "risk_level": "high", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Emerging multidrug-resistant pathogen causing nosocomial outbreaks of bloodstream infections."},
    {"scientific_name": "Plesiomonas shigelloides", "common_name": "Plesiomonas", "phylum": "Pseudomonadota", "class_name": "Gammaproteobacteria", "order_name": "Vibrionales", "family": "Pasteurellaceae", "genus": "Plesiomonas", "species": "shigelloides", "gram_stain": "negative", "shape": "rod", "size_micrometers": "1.0", "arrangement": "single", "oxygen_requirement": "facultative anaerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Freshwater, brackish water", "culture_media": "MacConkey agar, SS agar", "biosafety_level": 2, "risk_level": "low", "is_beneficial": False, "is_pathogenic": True, "is_opportunistic": True, "description": "Waterborne organism causing gastroenteritis; associated with freshwater fish and shellfish consumption."},
    {"scientific_name": "Cupriavidus metallidurans", "common_name": "Cupriavidus", "phylum": "Pseudomonadota", "class_name": "Betaproteobacteria", "order_name": "Burkholderiales", "family": "Burkholderiaceae", "genus": "Cupriavidus", "species": "metallidurans", "gram_stain": "negative", "shape": "rod", "size_micrometers": "2.0", "arrangement": "single", "oxygen_requirement": "aerobe", "motility": "motile", "spore_formation": False, "growth_temperature_optimal": 30.0, "habitat": "Soil contaminated with heavy metals", "culture_media": "Nutrient agar with heavy metals", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Remarkable heavy metal resistance; plays a role in biogenic gold formation through nanoparticle precipitation."},
    {"scientific_name": "Faecalibacterium prausnitzii", "common_name": "F. prausnitzii", "phylum": "Bacillota", "class_name": "Clostridia", "order_name": "Eubacteriales", "family": "Oxalobacteraceae", "genus": "Faecalibacterium", "species": "prausnitzii", "gram_stain": "positive", "shape": "rod", "size_micrometers": "3.0", "arrangement": "single", "oxygen_requirement": "anaerobe", "motility": "non-motile", "spore_formation": False, "growth_temperature_optimal": 37.0, "habitat": "Human colon", "culture_media": "Anaerobic blood agar with fructose", "biosafety_level": 1, "risk_level": "low", "is_beneficial": True, "is_pathogenic": False, "is_opportunistic": False, "description": "Most abundant anti-inflammatory bacterium in the human gut; major butyrate producer protective against IBD."},
]

DEDUPLICATE_NAMES = set()

NEW_DISEASES = [
    ("Syphilis", "A53.9", "Sexually Transmitted", "high", "Sexually transmitted infection caused by T. pallidum"),
    ("Lyme Disease", "A69.20", "Vector-borne", "moderate", "Tick-borne illness caused by B. burgdorferi"),
    ("Rocky Mountain Spotted Fever", "A77.0", "Vector-borne", "critical", "Tick-borne rickettsial infection"),
    ("Chlamydia", "A74.9", "Sexually Transmitted", "moderate", "Most common bacterial STI worldwide"),
    ("Legionnaires Disease", "J17.8", "Respiratory", "severe", "Severe pneumonia caused by Legionella"),
    ("Pertussis", "A37.9", "Respiratory", "high", "Whooping cough caused by B. pertussis"),
    ("Gastric Ulcer", "K25.9", "Gastrointestinal", "moderate", "Peptic ulcer disease associated with H. pylori"),
    ("Leptospirosis", "A27.9", "Systemic", "high", "Zoonotic febrile illness from Leptospira"),
    ("Brucellosis", "A23.9", "Systemic", "high", "Zoonotic undulant fever from Brucella"),
    ("Q Fever", "A78", "Systemic", "moderate", "Coxiella burnetii infection from livestock"),
    ("Gonorrhea", "A54.9", "Sexually Transmitted", "high", "STI caused by N. gonorrhoeae"),
    ("Cat Scratch Disease", "A28.1", "Vector-borne", "moderate", "Lymphadenopathy from B. henselae"),
    ("Trench Fever", "A79.0", "Vector-borne", "moderate", "Louse-borne B. quintana infection"),
    ("Periodontal Disease", "K05.3", "Oral", "moderate", "Chronic periodontitis from anaerobic bacteria"),
    ("Bacterial Vaginosis", "N76.0", "Gynecological", "low", "Vaginal dysbiosis with G. vaginalis"),
    ("Rat-Bite Fever", "A25.9", "Zoonotic", "moderate", "Infection from rat-bite pathogens"),
]

DISEASE_SPECIES_LINKS = {
    "Syphilis": ["Treponema pallidum"],
    "Lyme Disease": ["Borrelia burgdorferi"],
    "Rocky Mountain Spotted Fever": ["Rickettsia rickettsii"],
    "Chlamydia": ["Chlamydia trachomatis"],
    "Legionnaires Disease": ["Legionella pneumophila"],
    "Pertussis": ["Bordetella pertussis"],
    "Gastric Ulcer": ["Helicobacter pylori"],
    "Leptospirosis": ["Leptospira interrogans"],
    "Brucellosis": ["Brucella melitensis"],
    "Q Fever": ["Coxiella burnetii"],
    "Gonorrhea": ["Neisseria gonorrhoeae"],
    "Cat Scratch Disease": ["Bartonella henselae"],
    "Trench Fever": ["Bartonella quintana"],
    "Periodontal Disease": ["Porphyromonas gingivalis", "Treponema denticola", "Fusobacterium nucleatum", "Prevotella intermedia"],
    "Bacterial Vaginosis": ["Gardnerella vaginalis"],
    "Pneumonia": ["Mycoplasma pneumoniae", "Chlamydophila pneumoniae", "Legionella pneumophila", "Acinetobacter baumannii", "Stenotrophomonas maltophilia"],
    "Urinary Tract Infection": ["Proteus mirabilis", "Morganella morganii", "Staphylococcus saprophyticus", "Klebsiella oxytoca", "Enterobacter aerogenes", "Citrobacter freundii", "Serratia marcescens", "Providencia stuartii", "Aerococcus urinae", "Gardnerella vaginalis"],
    "Meningitis": ["Streptococcus agalactiae", "Kingella kingae"],
    "Sepsis": ["Acinetobacter baumannii", "Stenotrophomonas maltophilia", "Enterobacter aerogenes", "Serratia marcescens", "Citrobacter freundii", "Morganella morganii"],
    "Food Poisoning": ["Vibrio parahaemolyticus", "Vibrio vulnificus", "Aeromonas hydrophila", "Plesiomonas shigelloides", "Edwardsiella tarda"],
}

NEW_VIRULENCE_FACTORS = [
    ("Treponema pallidum", "T pallidum lipoproteins", "Lipoprotein", "Activates TLR2 triggering inflammatory cascade", "Endothelial cells", "tp47"),
    ("Borrelia burgdorferi", "Outer surface protein A", "Adhesin", "Mediates attachment to tick midgut and host tissues", "Vascular endothelium", "ospA"),
    ("Borrelia burgdorferi", "OspC", "Adhesin", "Essential for mammalian host infection", "Dermal tissue", "ospC"),
    ("Helicobacter pylori", "CagA", "Effector protein", "Injected via Type IV secretion, disrupts cell signaling", "Gastric epithelial cells", "cagA"),
    ("Helicobacter pylori", "VacA", "Pore-forming toxin", "Forms pores causing vacuolation and apoptosis", "Gastric epithelial cells", "vacA"),
    ("Helicobacter pylori", "Urease", "Enzyme", "Neutralizes gastric acid allowing stomach colonization", "Gastric mucosa", "ureA"),
    ("Legionella pneumophila", "Legiolysin", "Pore-forming toxin", "Facilitates intracellular survival in macrophages", "Macrophages", "lly"),
    ("Legionella pneumophila", "Type IV secretion system", "Secretion system", "Injects effector proteins into host cells", "Macrophages", "dotB"),
    ("Acinetobacter baumannii", "OmpA", "Outer membrane protein", "Mediates biofilm formation and serum resistance", "Epithelial cells", "ompA"),
    ("Acinetobacter baumannii", "Capsular polysaccharide", "Capsule", "Inhibits phagocytosis and complement activation", "Immune system", "cps"),
    ("Bordetella pertussis", "Pertussis toxin", "AB5 toxin", "ADP-ribosylation of G-protein causing lymphocytosis", "Respiratory epithelium", "ptx"),
    ("Bordetella pertussis", "Adenylate cyclase toxin", "AC toxin", "Elevates cAMP paralyzing immune cells", "Leukocytes", "cyaA"),
    ("Corynebacterium diphtheriae", "Diphtheria toxin", "AB toxin", "Inhibits protein synthesis via EF-2 ADP-ribosylation", "Various cells", "tox"),
    ("Chlamydia trachomatis", "Polymorphic membrane proteins", "Outer membrane protein", "Mediates adhesion and immune evasion", "Mucosal epithelium", "pmp"),
    ("Neisseria gonorrhoeae", "Opa proteins", "Adhesin", "Mediates attachment to epithelial and immune cells", "Mucosal epithelium", "opa"),
    ("Streptococcus agalactiae", "Group B streptococcal capsule", "Capsule", "Anti-phagocytic polysaccharide capsule", "Immune system", "cps"),
    ("Streptococcus agalactiae", "CAMP factor", "Hemolysin", "Synergizes with S. aureus beta-hemolysin for cell lysis", "Red blood cells", "cylE"),
    ("Porphyromonas gingivalis", "Gingipains", "Cysteine protease", "Degrades host proteins and disrupts immune response", "Oral tissues", "rgpA"),
    ("Fusobacterium nucleatum", "FadA", "Adhesin", "Invades epithelial cells and activates beta-catenin signaling", "Colonic epithelium", "fadA"),
    ("Bartonella henselae", "BadA", "Adhesin", "Mediates attachment to endothelial cells", "Endothelial cells", "badA"),
]

NEW_ANTIBIOTIC_RESISTANCE = [
    ("Acinetobacter baumannii", "Carbapenems", "OXA-type carbapenemase", "blaOXA-23", "resistant"),
    ("Acinetobacter baumannii", "Aminoglycosides", "Aminoglycoside modifying enzymes", "aac(6')-Ib", "resistant"),
    ("Acinetobacter baumannii", "Polymyxins", "LPS modification", "pmrB", "intermediate"),
    ("Neisseria gonorrhoeae", "Ciprofloxacin", "DNA gyrase mutation", "gyrA", "resistant"),
    ("Neisseria gonorrhoeae", "Ceftriaxone", "Penicillin-binding protein modification", "penA", "intermediate"),
    ("Stenotrophomonas maltophilia", "Carbapenems", "L1 metallo-beta-lactamase", "blaL1", "resistant"),
    ("Stenotrophomonas maltophilia", "Trimethoprim-sulfamethoxazole", "DfrA gene", "dfrA", "sensitive"),
    ("Streptococcus agalactiae", "Clindamycin", "Ribosomal methylation", "ermB", "resistant"),
    ("Helicobacter pylori", "Clarithromycin", "23S rRNA mutation", "23S", "resistant"),
    ("Helicobacter pylori", "Metronidazole", "Nitroreductase mutation", "rdxA", "resistant"),
    ("Proteus mirabilis", "Ampicillin", "Beta-lactamase production", "blaTEM", "resistant"),
    ("Morganella morganii", "Ampicillin", "Chromosomal beta-lactamase", "none", "resistant"),
    ("Serratia marcescens", "Ampicillin", "SHV-1 beta-lactamase", "blaSHV", "resistant"),
    ("Klebsiella oxytoca", "Ampicillin", "Beta-lactamase production", "blaTEM", "resistant"),
]

NEW_LAB_TESTS = [
    ("Treponema pallidum", "RPR", "Serological", "Blood", "Rapid plasma reagin screening", "Non-treponemal antibody", 0.85, 0.87, "1 hour"),
    ("Treponema pallidum", "TP-PA", "Serological", "Blood", "T. pallidum particle agglutination", "Treponemal antibody", 0.95, 0.99, "4 hours"),
    ("Borrelia burgdorferi", "ELISA", "Serological", "Blood", "Two-tier testing algorithm", "IgM/IgG antibodies", 0.90, 0.95, "24 hours"),
    ("Borrelia burgdorferi", "Western Blot", "Immunological", "Blood", "Confirmatory antibody detection", "Specific bands", 0.95, 0.99, "48 hours"),
    ("Helicobacter pylori", "Urea Breath Test", "Biochemical", "Breath", "13C-urea breath test", "Labeled CO2", 0.95, 0.95, "30 minutes"),
    ("Helicobacter pylori", "Rapid Urease Test", "Biochemical", "Biopsy", "Gastric biopsy urease test", "Color change", 0.92, 0.98, "1 hour"),
    ("Helicobacter pylori", "H. pylori Stool Ag", "Immunological", "Stool", "Enzyme immunoassay", "Antigen detection", 0.90, 0.95, "4 hours"),
    ("Chlamydia trachomatis", "NAAT", "Molecular", "Urine/swab", "Nucleic acid amplification test", "CT DNA/RNA", 0.97, 0.99, "4 hours"),
    ("Neisseria gonorrhoeae", "NAAT", "Molecular", "Urine/swab", "Nucleic acid amplification test", "GC DNA/RNA", 0.97, 0.99, "4 hours"),
    ("Neisseria gonorrhoeae", "Culture", "Microbiological", "Urine/swab", "Thayer-Martin selective agar", "Oxidase-positive colonies", 0.85, 0.99, "48 hours"),
    ("Legionella pneumophila", "Urinary Antigen", "Immunological", "Urine", "Lateral flow immunoassay", "Serogroup 1 antigen", 0.80, 0.99, "15 minutes"),
    ("Legionella pneumophila", "Culture", "Microbiological", "Sputum/BAL", "BCYE selective agar", "Colonies on BCYE not on blood agar", 0.85, 0.99, "5 days"),
    ("Bordetella pertussis", "PCR", "Molecular", "Nasopharyngeal swab", "Real-time PCR for IS481", "Bordetella DNA", 0.95, 0.98, "4 hours"),
    ("Corynebacterium diphtheriae", "Albert Stain", "Microscopy", "Throat swab", "Albert staining method", "Metachromatic granules", 0.80, 0.85, "1 hour"),
    ("Mycoplasma pneumoniae", "PCR", "Molecular", "Throat swab", "Real-time PCR", "M. pneumoniae DNA", 0.95, 0.98, "4 hours"),
    ("Mycoplasma pneumoniae", "Cold Agglutinin Test", "Serological", "Blood", "IgM cold agglutinin", "Titers > 1:64", 0.70, 0.80, "4 hours"),
    ("Bartonella henselae", "IFA", "Serological", "Blood", "Immunofluorescence assay", "Bartonella IgG/IgM", 0.85, 0.90, "48 hours"),
    ("Brucella melitensis", "SAT", "Serological", "Blood", "Standard agglutination test", "Brucella antibodies", 0.90, 0.95, "24 hours"),
    ("Cutibacterium acnes", "Culture", "Microbiological", "Tissue/aspirate", "Anaerobic culture", "Small white colonies", 0.70, 0.95, "5-7 days"),
    ("Fusobacterium nucleatum", "PCR", "Molecular", "Tissue/blood", "16S rRNA PCR", "F. nucleatum DNA", 0.95, 0.98, "24 hours"),
]

NEW_BENEFICIAL = [
    ("Faecalibacterium prausnitzii", "Probiotic", "Major butyrate producer with anti-inflammatory properties", "Reduces intestinal inflammation via butyrate", "Metabolic health", "Next-generation probiotic candidate"),
    ("Roseburia intestinalis", "Probiotic", "Butyrate-producing gut commensal", "Reduces inflammation and improves gut barrier", "Gut health", "Potential IBD therapy"),
    ("Ruminococcus bromii", "Industrial", "Keystone starch degrader in colon", "Breaks down resistant starch for other gut bacteria", "Prebiotic synergy", "Resistant starch fermentation"),
    ("Bifidobacterium longum", "Probiotic", "Supports immune function and gut barrier", "Short-chain fatty acid production", "Vitamin synthesis", "Fermented dairy"),
    ("Streptomyces griseus", "Industrial", "Source of streptomycin antibiotic", "Aminoglycoside antibiotic production", "Antibiotic production", "Soil antibiotic synthesis"),
    ("Bacillus thuringiensis", "Industrial", "Produces insecticidal Cry proteins", "Crystal proteins toxic to insect larvae", "Biopesticide production", "Organic farming"),
    ("Deinococcus radiodurans", "Industrial", "Extremely radiation resistant organism", "Efficient DNA repair mechanisms", "Bioremediation", "Radiation research"),
    ("Geobacter sulfurreducens", "Industrial", "Electroactive bacterium for bioelectronics", "Extracellular electron transfer", "Microbial fuel cells", "Bioremediation"),
    ("Shewanella oneidensis", "Industrial", "Model organism for electron transfer", "Extracellular electron transfer to metals", "Bioelectronics", "Metal bioremediation"),
    ("Agrobacterium tumefaciens", "Industrial", "Tool for plant genetic engineering", "T-DNA transfer system for transgenic plants", "Plant biotechnology", "Transgenic crop production"),
    ("Thermus aquaticus", "Industrial", "Source of Taq DNA polymerase", "Thermostable DNA polymerase for PCR", "Molecular biology", "PCR diagnostics"),
    ("Rhizobium leguminosarum", "Agricultural", "Nitrogen-fixing symbiont for legumes", "Biological nitrogen fixation in root nodules", "Sustainable agriculture", "Legume production"),
    ("Bradyrhizobium japonicum", "Agricultural", "Soybean nitrogen-fixing symbiont", "Nitrogen fixation specific to soybeans", "Soybean production", "Agricultural sustainability"),
    ("Azotobacter vinelandii", "Agricultural", "Free-living nitrogen fixer", "Biological nitrogen fixation in soil", "Soil fertility", "Agricultural inoculants"),
    ("Bacillus licheniformis", "Industrial", "Industrial enzyme production", "Amylase and protease production", "Detergent enzymes", "Textile processing"),
    ("Bacillus megaterium", "Industrial", "Phosphate solubilizer and vitamin producer", "Solubilizes inorganic phosphate for plants", "Biofertilizer", "Vitamin B12 production"),
    ("Propionibacterium freudenreichii", "Probiotic", "Swiss cheese bacterium with probiotic effects", "Produces propionic acid and vitamin B12", "Dairy fermentation", "Swiss cheese production"),
    ("Leuconostoc mesenteroides", "Industrial", "Primary fermentation starter", "Produces CO2 and lactic acid", "Vegetable fermentation", "Sauerkraut, kimchi"),
    ("Pediococcus acidilactici", "Probiotic", "Lactic acid bacterium for food preservation", "Produces pediocin antimicrobial peptides", "Meat fermentation", "Silage production"),
    ("Oenococcus oeni", "Industrial", "Wine malolactic fermentation specialist", "Converts malic acid to lactic acid", "Winemaking", "Wine acid reduction"),
]


def seed_expanded():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()

    existing_names = {s.scientific_name for s in db.query(BacterialSpecies.scientific_name).all()}
    existing_disease_names = {d.name for d in db.query(Disease.name).all()}
    new_species_map = {}

    count = 0
    for sp_data in NEW_SPECIES:
        if sp_data["scientific_name"] in existing_names or sp_data["scientific_name"] in DEDUPLICATE_NAMES:
            continue
        DEDUPLICATE_NAMES.add(sp_data["scientific_name"])
        sp = BacterialSpecies(**sp_data)
        db.add(sp)
        db.flush()
        new_species_map[sp.scientific_name] = sp.id
        count += 1

    new_disease_count = 0
    for name, icd, cat, sev, desc in NEW_DISEASES:
        if name not in existing_disease_names:
            d = Disease(name=name, icd10_code=icd, category=cat, severity=sev, description=desc)
            db.add(d)
            db.flush()
            existing_disease_names.add(name)
            new_disease_count += 1

    all_disease_map = {d.name: d.id for d in db.query(Disease).all()}

    link_count = 0
    for disease_name, sp_names in DISEASE_SPECIES_LINKS.items():
        did = all_disease_map.get(disease_name)
        if not did:
            continue
        for sn in sp_names:
            sid = new_species_map.get(sn)
            if sid:
                db.add(SpeciesDisease(species_id=sid, disease_id=did))
                link_count += 1

    vf_count = 0
    for sp_name, name, vtype, mech, target, gene in NEW_VIRULENCE_FACTORS:
        sid = new_species_map.get(sp_name)
        if sid:
            db.add(VirulenceFactor(species_id=sid, name=name, type=vtype, mechanism=mech, target_tissue=target, gene_name=gene))
            vf_count += 1

    ar_count = 0
    for sp_name, abx, mech, gene, susc in NEW_ANTIBIOTIC_RESISTANCE:
        sid = new_species_map.get(sp_name)
        if sid:
            db.add(AntibioticResistance(species_id=sid, antibiotic_name=abx, resistance_mechanism=mech, resistance_gene=gene, susceptibility=susc))
            ar_count += 1

    lt_count = 0
    for sp_name, tname, ttype, spec, meth, exp, sens, spec_val, tat in NEW_LAB_TESTS:
        sid = new_species_map.get(sp_name)
        if sid:
            db.add(LabTest(species_id=sid, test_name=tname, test_type=ttype, specimen_type=spec, methodology=meth, expected_result=exp, sensitivity=sens, specificity=spec_val, turnaround_time=tat))
            lt_count += 1

    bp_count = 0
    for sp_name, ptype, desc, health, industrial, food in NEW_BENEFICIAL:
        sid = new_species_map.get(sp_name)
        if sid:
            db.add(BeneficialProperty(species_id=sid, property_type=ptype, description=desc, health_benefit=health, industrial_use=industrial, food_application=food))
            bp_count += 1

    db.commit()

    total_species = db.query(BacterialSpecies).count()
    total_diseases = db.query(Disease).count()
    total_symptoms = db.query(Symptom).count()
    total_vf = db.query(VirulenceFactor).count()
    total_ar = db.query(AntibioticResistance).count()
    total_lt = db.query(LabTest).count()
    total_bp = db.query(BeneficialProperty).count()
    db.close()

    print(f"Expanded seed complete!")
    print(f"  New species inserted: {count}")
    print(f"  New diseases: {new_disease_count}")
    print(f"  Disease-species links: {link_count}")
    print(f"  Virulence factors: {vf_count}")
    print(f"  Antibiotic resistance: {ar_count}")
    print(f"  Lab tests: {lt_count}")
    print(f"  Beneficial properties: {bp_count}")
    print(f"  Totals: {total_species} species, {total_diseases} diseases, {total_symptoms} symptoms")
    print(f"  Totals: {total_vf} VF, {total_ar} AR, {total_lt} lab tests, {total_bp} beneficial properties")


if __name__ == "__main__":
    seed_expanded()
