"""initial schema

Revision ID: d3e7561e38bb
Revises: 
Create Date: 2026-07-18 16:38:39.713019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e7561e38bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bacterial_species',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=True),
    sa.Column('kingdom', sa.String(length=100), nullable=True),
    sa.Column('phylum', sa.String(length=100), nullable=True),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('order_name', sa.String(length=100), nullable=True),
    sa.Column('family', sa.String(length=100), nullable=True),
    sa.Column('genus', sa.String(length=100), nullable=True),
    sa.Column('species', sa.String(length=100), nullable=True),
    sa.Column('gram_stain', sa.String(length=50), nullable=True),
    sa.Column('shape', sa.String(length=100), nullable=True),
    sa.Column('size_micrometers', sa.String(length=50), nullable=True),
    sa.Column('arrangement', sa.String(length=100), nullable=True),
    sa.Column('oxygen_requirement', sa.String(length=100), nullable=True),
    sa.Column('motility', sa.String(length=100), nullable=True),
    sa.Column('spore_formation', sa.Boolean(), nullable=True),
    sa.Column('growth_temperature_optimal', sa.Float(), nullable=True),
    sa.Column('habitat', sa.Text(), nullable=True),
    sa.Column('culture_media', sa.Text(), nullable=True),
    sa.Column('biosafety_level', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('is_beneficial', sa.Boolean(), nullable=True),
    sa.Column('is_pathogenic', sa.Boolean(), nullable=True),
    sa.Column('is_opportunistic', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bacterial_species_scientific_name'), 'bacterial_species', ['scientific_name'], unique=True)
    op.create_table('diseases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icd10_code', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('symptoms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('symptoms_json', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('medical_history_json', sa.Text(), nullable=True),
    sa.Column('travel_history', sa.Text(), nullable=True),
    sa.Column('top_candidate', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('antibiotic_resistance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('antibiotic_name', sa.String(length=255), nullable=False),
    sa.Column('resistance_mechanism', sa.Text(), nullable=True),
    sa.Column('resistance_gene', sa.String(length=100), nullable=True),
    sa.Column('susceptibility', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['bacterial_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beneficial_properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('property_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('health_benefit', sa.Text(), nullable=True),
    sa.Column('industrial_use', sa.Text(), nullable=True),
    sa.Column('food_application', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['bacterial_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enzymes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('enzyme_name', sa.String(length=255), nullable=False),
    sa.Column('ec_number', sa.String(length=50), nullable=True),
    sa.Column('function_description', sa.Text(), nullable=True),
    sa.Column('substrate', sa.String(length=255), nullable=True),
    sa.Column('industrial_use', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['bacterial_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('immune_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('immune_pathway', sa.String(length=255), nullable=True),
    sa.Column('response_type', sa.String(length=100), nullable=True),
    sa.Column('cytokine_profile', sa.Text(), nullable=True),
    sa.Column('immune_evasion_mechanism', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['bacterial_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('test_type', sa.String(length=100), nullable=True),
    sa.Column('specimen_type', sa.String(length=100), nullable=True),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('sensitivity', sa.Float(), nullable=True),
    sa.Column('specificity', sa.Float(), nullable=True),
    sa.Column('turnaround_time', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['bacterial_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protein_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('protein_name', sa.String(length=255), nullable=False),
    sa.Column('uniprot_id', sa.String(length=50), nullable=True),
    sa.Column('gene_name', sa.String(length=100), nullable=True),
    sa.Column('molecular_weight_kda', sa.Float(), nullable=True),
    sa.Column('function_description', sa.Text(), nullable=True),
    sa.Column('clinical_relevance', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['bacterial_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species_diseases',
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('association_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['bacterial_species.id'], ),
    sa.PrimaryKeyConstraint('species_id', 'disease_id')
    )
    op.create_table('toxins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('toxin_name', sa.String(length=255), nullable=False),
    sa.Column('toxin_type', sa.String(length=100), nullable=True),
    sa.Column('mechanism_of_action', sa.Text(), nullable=True),
    sa.Column('target_cells', sa.String(length=255), nullable=True),
    sa.Column('heat_stability', sa.String(length=50), nullable=True),
    sa.Column('clinical_effect', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['bacterial_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('virulence_factors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('target_tissue', sa.String(length=255), nullable=True),
    sa.Column('gene_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['bacterial_species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virulence_factors')
    op.drop_table('toxins')
    op.drop_table('species_diseases')
    op.drop_table('protein_profiles')
    op.drop_table('lab_tests')
    op.drop_table('immune_responses')
    op.drop_table('enzymes')
    op.drop_table('beneficial_properties')
    op.drop_table('antibiotic_resistance')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('symptoms')
    op.drop_table('diseases')
    op.drop_index(op.f('ix_bacterial_species_scientific_name'), table_name='bacterial_species')
    op.drop_table('bacterial_species')
    # ### end Alembic commands ###
